name: Invoice Check Health Check - Daily 8AM IST

on:
  schedule:
    - cron: "0 * * * *" # 8:00 AM IST daily
  workflow_dispatch:

jobs:
  show-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Get public IP
        run: |
          curl https://api.ipify.org
          echo

  run-tests:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      BASE_URL: ${{ secrets.BASE_URL }}
      VALID_USERNAME: ${{ secrets.VALID_USERNAME }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
      BROWSER: ${{ secrets.BROWSER }}
      TIMEOUT: ${{ secrets.TIMEOUT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Print Trigger Time
        run: |
          echo "UTC:"
          date -u
          echo "Runner Time:"
          date

      - name: Run Health Check
        run: |
          robot --variable HEADLESS:True -d results -t "Verify Valid Login" Testcases/login_testcases.robot

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: health-check-results
          path: results/
