name: Invoice Check 7AM IST
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      BASE_URL: ${{ secrets.BASE_URL }}
      VALID_USERNAME: ${{ secrets.VALID_USERNAME }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
      BROWSER: ${{ secrets.BROWSER }}
      TIMEOUT: ${{ secrets.TIMEOUT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Print Trigger Time
        run: |
          echo "UTC:"
          date -u
          echo "Runner Time:"
          date

      - name: Whitelist Runner IP
        run: |
          RUNNER_IP=$(curl -s https://api.ipify.org)
          echo "Runner IP: $RUNNER_IP"
          curl -s -X POST "${{ secrets.WHITELIST_API_URL }}" \
            -H "Content-Type: application/json" \
            -u "${{ secrets.VALID_USERNAME }}:${{ secrets.VALID_PASSWORD }}"
            -d "{\"ip\": \"$RUNNER_IP\"}"

      - name: Wait for whitelist to propagate
        run: sleep 5

      - name: Run State Wise Data Loading Test
        run: |
          robot --variable HEADLESS:True -d results -t "Validate State Wise Data Loading" Testcases/InvoiceCheck/dashboard_testcases.robot

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: state-wise-data-load-results
          path: results/
