name: Invoice Check 7AM IST

on:
  schedule:
    - cron: "30 1 * * *" # 7:00 AM IST
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      BASE_URL: ${{ secrets.BASE_URL }}
      VALID_USERNAME: ${{ secrets.VALID_USERNAME }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
      BROWSER: ${{ secrets.BROWSER }}
      TIMEOUT: ${{ secrets.TIMEOUT }}
      INVALID_USERNAME: ${{ secrets.INVALID_USERNAME }}
      INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}
      VALID_NON_PO_USERNAME: ${{ secrets.VALID_NON_PO_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Print Trigger Time
        run: |
          echo "UTC:"
          date -u
          echo "Runner Time:"
          date

      - name: Run Robot Framework test
        run: |
          robot --variable HEADLESS:True -d results -t "Validate State Wise Data Loading" Testcases/InvoiceCheck/dashboard_testcases.robot

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
